* Survey 

** Brief Description

- A Survey is made up of Questions. The Survey tracks answers recorded for its questions, and determines which questions are active based on the optional condition associated with question.

- Each Question has:
    - a unique /tag/ to idendify that Question
    - an optional /condition/ that at runtime can be used to determine if
    the question is active or not.

- The /condition/ is a string, matching a lisp-style expression. It supports the following operations:
    - (and boolean-exp-1 boolean-exp-2)
    - (or boolean-exp-1 boolean-exp-2)
    - (equals string-exp-1 string-exp-2)
    - (includes array-exp string-exp)
    - (answer Identifier)

- When the Survey records an answer for a Question it updates the state for the questions that follow it:
    - if a question changes its state from what was previously recorded, the Survey re-evaluates the following questions to see if their state needs to change
    - essentially this means they Survey keeps recursing over the remaining questions as needed to keep the state of each question consistent with the optional condition.

** Conditions

Conditions can be nested indefinitely as long as they conform to the grammar for this conditonal expression.

I should define the grammar more formally, but the few examples below will help illustrate what you can do with conditions.

*** equals -- compares two string expressions

#+BEGIN_SRC js
    const exp1 = "(equals 'a' 'b')"
    new Condition(new Survey()).evaluate(exp1) == false

    const exp2 = "(equals 'a' 'a')"  => true
    new Condition(new Survey()).evaluate(exp2) == true
#+END_SRC

*** not -- negates an expression that it wraps

#+BEGIN_SRC js
    const exp = "(not (equals 'a' 'b'))"
    new Condition(new Survey()).evaluate(exp) == true
#+END_SRC

*** answer
    it needs to look up an answer in the survey and return the value

#+BEGIN_SRC js
    const question: Question = {
      tag: "q1",
      conditionExp: exp,
    };
    const survey = new Survey().question(question);
    survey.recordAnswer('q1' 'hello')
    const exp1 = "(equals (answer q1) 'hello')"
    new Condition(survey).evaluate(exp1) == true
    const exp2 = "(equals (answer q1) 'hellowse')"
    new Condition(survey).evaluate(exp2) == false
#+END_SRC

*** includes - similar to equal, but it looks up a string in a list of strings

#+BEGIN_SRC js
    // simple example:
    const exp1 = "(includes ['a', 'b'] 'b')"
    new Condition(new Survey()).evaluate(exp1) == true

    // with answer:
    const question: Question = {
      tag: "q1",
    };
    const survey = new Survey().question(question);
    survey.recordAnswer('q1', ['a', 'b'])

    const exp2 = "(includes (answer q1) 'c')"
    new Condition(survey).evaluate(exp2) == false
#+END_SRC

*** and
    - expects two expressions
    - evaluates them left to right
    - stops the valuation if it detects false and returns false
    - this example pulls in multiple expressions to make it more interesting
#+BEGIN_SRC js
    const question1: Question = {
      tag: "q1",
      conditionExp: exp,
    };
    const question2: Question = {
      tag: "q2",
      conditionExp: exp,
    };
    const survey = new Survey().question(question1).question(question2);
    survey.recordAnswer('q1', 'hello')
    survey.recordAnswer('q2', 'there') 
    const exp = "(not (and (equals (answer q1) "hello") (equals 'there' (answer q2))))" 
    new Condition(survey).evaluate(exp) == false
#+END_SRC

*** or
    - expects two expressions
    - evaluates them left to right
    - stops the valuation if it detects true and returns true
